DATA SEGMENT
    BLOCK DB -5,20,10H,18,45H,66H,8EH,5FH,0DDH,22H,33H,11H,78H,98,0,100B,45H,6EH,45,23H
    COUNT = $ - BLOCK
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE, DS:DATA
START:
    MOV AX, DATA
    MOV DS, AX
    LEA SI, BLOCK
    MOV CX, COUNT
AGAIN:
    MOV AL, [SI]
    MOV DI, SI
    MOV DX, CX
NEXT1:
    CMP AL, [DI]
    JGE NEXT   ;AL>=[DI]
    XCHG AL, [DI]
NEXT:    
    INC DI
    DEC DX
    JNZ NEXT1
    MOV [SI], AL ;找出最大的，放到最前面
    INC SI
    LOOP AGAIN
EXIT:
    MOV AH, 4CH
    INT 21
CODE ENDS
    END START