;显示字符串“GOOD AFTERNOON”
DATA SEGMENT
	STRING DB 'GOOD AFTERNOON$'
DATA ENDS
CODE SEGMENT
	ASSUME CS:CODE, DS:DATA
START:
	MOV AX, DATA
	MOV DS, AX
	LEA SI, STRING
	MOV DX, SI
	MOV AH, 09H
	INT 21H
EXIT:
	MOV AH, 4CH
	INT 21H
CODE ENDS
	END START